/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as PaymentInfoRouteImport } from './routes/payment-info'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as ApiPaymentStorepayActionRouteImport } from './routes/api/payment/storepay.$action'
import { Route as ApiPaymentQpayActionRouteImport } from './routes/api/payment/qpay.$action'
import { Route as ApiPaymentPocketZeroActionRouteImport } from './routes/api/payment/pocket-zero.$action'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentInfoRoute = PaymentInfoRouteImport.update({
  id: '/payment-info',
  path: '/payment-info',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentStorepayActionRoute =
  ApiPaymentStorepayActionRouteImport.update({
    id: '/api/payment/storepay/$action',
    path: '/api/payment/storepay/$action',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentQpayActionRoute = ApiPaymentQpayActionRouteImport.update({
  id: '/api/payment/qpay/$action',
  path: '/api/payment/qpay/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentPocketZeroActionRoute =
  ApiPaymentPocketZeroActionRouteImport.update({
    id: '/api/payment/pocket-zero/$action',
    path: '/api/payment/pocket-zero/$action',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/payment-info': typeof PaymentInfoRoute
  '/track': typeof TrackRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/api/payment/pocket-zero/$action': typeof ApiPaymentPocketZeroActionRoute
  '/api/payment/qpay/$action': typeof ApiPaymentQpayActionRoute
  '/api/payment/storepay/$action': typeof ApiPaymentStorepayActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/payment-info': typeof PaymentInfoRoute
  '/track': typeof TrackRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/api/payment/pocket-zero/$action': typeof ApiPaymentPocketZeroActionRoute
  '/api/payment/qpay/$action': typeof ApiPaymentQpayActionRoute
  '/api/payment/storepay/$action': typeof ApiPaymentStorepayActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/payment-info': typeof PaymentInfoRoute
  '/track': typeof TrackRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/api/payment/pocket-zero/$action': typeof ApiPaymentPocketZeroActionRoute
  '/api/payment/qpay/$action': typeof ApiPaymentQpayActionRoute
  '/api/payment/storepay/$action': typeof ApiPaymentStorepayActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/payment-info'
    | '/track'
    | '/order/$orderNumber'
    | '/products/$slug'
    | '/products/'
    | '/api/payment/pocket-zero/$action'
    | '/api/payment/qpay/$action'
    | '/api/payment/storepay/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/payment-info'
    | '/track'
    | '/order/$orderNumber'
    | '/products/$slug'
    | '/products'
    | '/api/payment/pocket-zero/$action'
    | '/api/payment/qpay/$action'
    | '/api/payment/storepay/$action'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/payment-info'
    | '/track'
    | '/order/$orderNumber'
    | '/products/$slug'
    | '/products/'
    | '/api/payment/pocket-zero/$action'
    | '/api/payment/qpay/$action'
    | '/api/payment/storepay/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  PaymentInfoRoute: typeof PaymentInfoRoute
  TrackRoute: typeof TrackRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiPaymentPocketZeroActionRoute: typeof ApiPaymentPocketZeroActionRoute
  ApiPaymentQpayActionRoute: typeof ApiPaymentQpayActionRoute
  ApiPaymentStorepayActionRoute: typeof ApiPaymentStorepayActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-info': {
      id: '/payment-info'
      path: '/payment-info'
      fullPath: '/payment-info'
      preLoaderRoute: typeof PaymentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/storepay/$action': {
      id: '/api/payment/storepay/$action'
      path: '/api/payment/storepay/$action'
      fullPath: '/api/payment/storepay/$action'
      preLoaderRoute: typeof ApiPaymentStorepayActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/qpay/$action': {
      id: '/api/payment/qpay/$action'
      path: '/api/payment/qpay/$action'
      fullPath: '/api/payment/qpay/$action'
      preLoaderRoute: typeof ApiPaymentQpayActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/pocket-zero/$action': {
      id: '/api/payment/pocket-zero/$action'
      path: '/api/payment/pocket-zero/$action'
      fullPath: '/api/payment/pocket-zero/$action'
      preLoaderRoute: typeof ApiPaymentPocketZeroActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  PaymentInfoRoute: PaymentInfoRoute,
  TrackRoute: TrackRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiPaymentPocketZeroActionRoute: ApiPaymentPocketZeroActionRoute,
  ApiPaymentQpayActionRoute: ApiPaymentQpayActionRoute,
  ApiPaymentStorepayActionRoute: ApiPaymentStorepayActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
